PATH="/opt/android-sdk/cmdline-tools/latest/bin/:$PATH"
PATH="$PATH:$HOME/.local/bin"
PATH="$PATH:$HOME/.nix-profile/bin"
export PATH="$HOME/.pyenv/bin:$PATH"
#eval "$(pyenv init -)"
#eval "$(pyenv virtualenv-init -)"
